### PR TITLE
add `address` subcommand to encode/decode address to/from puzzle hash

### PR DESCRIPTION
**Pull request by leonid-ed**
This PR aims to add a new subcommand `address`:
- `address encode` to encode address to puzzle hash
- `address decode` to decode address from puzzle hash

Examples of usages:
```bash
$ coinset address encode xch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ks6e8mvy
{
  "address": "xch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ks6e8mvy",
  "puzzle_hash": "0x000000000000000000000000000000000000000000000000000000000000dead"
}

$ coinset address encode txch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ksh7qddh
{
  "address": "txch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ksh7qddh",
  "puzzle_hash": "0x000000000000000000000000000000000000000000000000000000000000dead"
}

$ coinset address decode 000000000000000000000000000000000000000000000000000000000000dead
{
  "address": "xch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ks6e8mvy",
  "puzzle_hash": "0x000000000000000000000000000000000000000000000000000000000000dead"
}

# it is allowed to pass puzzle hash argument values with the prefix '0x'
$ coinset address decode 0x000000000000000000000000000000000000000000000000000000000000dead
{
  "address": "xch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ks6e8mvy",
  "puzzle_hash": "0x000000000000000000000000000000000000000000000000000000000000dead"
}

# -t argument to use the testnet address prefix 'txch'
$ coinset address decode 000000000000000000000000000000000000000000000000000000000000dead -t
{
  "address": "txch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ksh7qddh",
  "puzzle_hash": "0x000000000000000000000000000000000000000000000000000000000000dead"
}
```

Also it adds the following help output for the new subcommand:
```bash
$ coinset address -h
Encode/decode address to/from puzzle hash.

Usage:
  coinset address [command]

Available Commands:
  decode      Decode address from puzzle hash
  encode      Encode address to puzzle hash

Flags:
  -h, --help   help for address

Global Flags:
  -q, --query string   filter to apply using jq syntax (default ".")
  -r, --raw            display output in raw json

Use "coinset address [command] --help" for more information about a command.
```

### CODE REVIEW

**Comment by cameroncooper** [comment]
Thank you for adding this. Sorry I didn't see it until now. I like what you've done here. I've thought about adding things like this from cdv. I'm inclined to merge it as-is but I'd like to take a minute to think about the precent and see if this is in line with how we might want to do similar features in the future.

**Comment by cameroncooper** [comment]
I think my main concern here is with the name `get_address_by_puzzle_hash` which looks like a RPC call but isn't. What would you think about using the `encode`/`decode` terminology used by `cdv`? Maybe `coinset address encode 0x00000...` and `coinset address decode txch1qqqqqqqq`. This leaves open opportunities for things like `coinset clvm encode` and `coinset clvm decode`.

What do you think @leonid-ed ?

**Comment by cameroncooper** [comment]
@cmmarslender is this version of `go-chia-libs` ok or should we update?

**Comment by cmmarslender** [comment]
> @cmmarslender is this version of `go-chia-libs` ok or should we update?

0.14.2 is latest, though the packages used here likely haven't changed since the version here (though that also should make this a fairly easy thing to update in the PR real quick)

**Comment by leonid-ed** [comment]
@cameroncooper Thank you for review! Yes, your suggestion makes sense, I agree. I've updated the PR accordingly, please take a look.

**Comment by leonid-ed** [comment]
@cameroncooper I've also bumped up [`go-chia-libs`](https://github.com/Chia-Network/go-chia-libs) version to `0.15.0` (the latest version released yesterday), but looks like it requires `go@1.21` and `go.mod` has been updated automatically, so now it also requires go version `1.21`.

If this is an issue, then let me know and I will revert that change.

**Comment by cameroncooper** [comment]
I just pushed some changes, please see if you like them.

I made some tweaks to the naming so it's like:

`coinset address decode <address>`
`coinset address encode <puzzle hash>`

I removed the JSON formatting from these results because it felt unnecessary since they were not coming from the RPC server, but tell me if you disagree. 

But while I was reverting the refactor to the JSON output, I made some tweaks while I was in there. I made it so you can use -q and -r at the saw time, which I thought would be nice.

**Comment by leonid-ed** [comment]
@cameroncooper Your changes look good to me! Thank you!

**Pull request merged**
